spring:
  application:
    name: boot
  mail:
    host: smtp.gmail.com
    port: 587
    username: fedykvitalik2004@gmail.com
    password: obqmhqoddappncoe
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
